services:
  mysql-db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: rest_book_db
#    volumes:
#      - ./data:/var/lib/mysql
    ports:
     - '3307:3306'

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: bootrest-book:1.0
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/rest_book_db' #?createDatabaseIfNotExist=true'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    ports:
      - '9898:9246'


